### ISSUE TITLE
Multiple errors 

### ISSUE THREAD

**Issue by onlinegill** [lmandres/GT06ScannerClient#5]
Hello, I am running latest OS on raspberry Pi but getting fowling error 

```

pi@raspberrypi:~/GT06ScannerClient $ python runClient.py
pygame 2.1.0 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Namespace(config='config.xml', id=None, server_address=None, server_port=None, update_delay=None, gps_port=None, gps_baud=None, maps_url=None, magnification=None, zoom=None)
Traceback (most recent call last):
  File "/home/pi/GT06ScannerClient/runClient.py", line 68, in <module>
    scanner = GT06ScannerClient.GT06ScannerClient(
  File "/home/pi/GT06ScannerClient/GT06ScannerClient.py", line 43, in __init__
    mapsMagnification = int(self.configReader.getMapsMagnification())
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by lmandres** [comment]
@onlinegill ,  Thank you for reporting this.  See the link below on the line that you need to add in config.xml:

https://github.com/lmandres/GT06ScannerClient/blob/master/config.xml#L16

**Comment by onlinegill** [comment]
Hi,

After adding to config 
<Magnification>1</Magnification>

now here is output

`pi@raspberrypi:~/GT06ScannerClient $ python runClient.py
pygame 2.1.0 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Namespace(config='config.xml', id=None, server_address=None, server_port=None, update_delay=None, gps_port=None, gps_baud=None, maps_url=None, magnification=None, zoom=None)
MESA-LOADER: failed to open vc4: /usr/lib/dri/vc4_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: vc4
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load swrast driver
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
MESA-LOADER: failed to open vc4: /usr/lib/dri/vc4_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: vc4
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load swrast driver
Traceback (most recent call last):
  File "/home/pi/GT06ScannerClient/runClient.py", line 68, in <module>
    scanner = GT06ScannerClient.GT06ScannerClient(
  File "/home/pi/GT06ScannerClient/GT06ScannerClient.py", line 64, in __init__
    self.displayLocation = displayLocation.DisplayLocation(
  File "/home/pi/GT06ScannerClient/displayLocation.py", line 34, in __init__
    self.screen = pygame.display.set_mode(
pygame.error: displayIndex must be in the range 0 - -1
pi@raspberrypi:~/GT06ScannerClient $
`

**Comment by lmandres** [comment]
Hi @onlinegill , are you running this in a GUI environment or from the command line without the graphical user interface?

**Comment by lmandres** [comment]
I'm trying to figure out how to replicate this on my Raspberry Pi.

**Comment by lmandres** [comment]
Also, do you have more than one screen attached to your Raspberry Pi?

**Comment by onlinegill** [comment]
> I noticed on the output that you are running pygame 2.1.0. Did you install the Python requirements using the following?
> 
> pip install -r requirements.txt
> 
> In my requirements.txt file, the pygame version is 1.9.6, so I have the feeling that you installed the pygame requirements separately.

I have raspberry pi zero w and I am using headless (no monitor connected to it only ssh)

I could not install with pip install -r requirements.txt because alot of them were giving error that it can't find so I installed individually one by one with latest versions.
All I wanted to plug pi to the car with gps module and connect pi to hotspot wifi

**Comment by lmandres** [comment]
@onlinegill .  Thank you.  I might have to make changes so that you can run it headless.  Let me see what I can fit into my schedule to allow it to run headless.

**Comment by lmandres** [comment]
Also, I'd be interested in what you have for an ESP32 project as well.

**Comment by lmandres** [comment]
@onlinegill , actually, try removing the DisplaySettings section in the XML file.  You won't get any output, but you should get updates on your Traccar server.  You can probably comment out the section like the following:

**Comment by onlinegill** [comment]
Let me how to contact you by email so we can talk about esp32. I can send you codes. If esp32 is working then I don't need to use expensive raspberrypi

**Comment by lmandres** [comment]
@onlinegill , email me at its.just.me@juno.com.  Thanks.

**Comment by onlinegill** [comment]
> @onlinegill , email me at [its.just.me@juno.com](mailto:its.just.me@juno.com). Thanks.

Sent you email

**Comment by lmandres** [comment]
@onlinegill , was the Pi Zero issue resolved by commenting out the section?

**Comment by onlinegill** [comment]
> @onlinegill , was the Pi Zero issue resolved by commenting out the section?

no. here are new error

```
pi@raspberrypi:~/GT06ScannerClient $ python runClient.py
pygame 2.1.0 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Namespace(config='config.xml', id=None, server_address=None, server_port=None, update_delay=None, gps_port=None, gps_baud=None, maps_url=None, magnification=None, zoom=None)
ERROR:root:Cannot connect to 144.91.75.79:5055
Traceback (most recent call last):
  File "/home/pi/GT06ScannerClient/gt06Client.py", line 45, in connect
    self.socket.connect((self.serverAddress, self.serverPort))
ConnectionRefusedError: [Errno 111] Connection refused
pi@raspberrypi:~/GT06ScannerClient $

```

**Comment by onlinegill** [comment]
> @onlinegill , was the Pi Zero issue resolved by commenting out the section?
Yes and no. 
Script runs now and i can see GPS information in terminal but does not post on traccar server

FYI : ESP32 client project here and its working. 
https://github.com/onlinegill/ESP32-Traccar-GPS

**Comment by lmandres** [comment]
> > @onlinegill , was the Pi Zero issue resolved by commenting out the section?
> > Yes and no.
> > Script runs now and I can see GPS information in terminal but it does not post on traccar server
> 
> FYI : ESP32 client project is here and its working. https://github.com/onlinegill/ESP32-Traccar-GPS

So, looking at your code, my code might not be working because my script is using the GT06 protocol rather than the Traccar REST API.

**Comment by onlinegill** [comment]
> > > @onlinegill , was the Pi Zero issue resolved by commenting out the section?
> > > Yes and no.
> > > Script runs now and I can see GPS information in terminal but it does not post on traccar server
> > 
> > 
> > FYI : ESP32 client project is here and its working. https://github.com/onlinegill/ESP32-Traccar-GPS
> 
> So, looking at your code, my code might not be working because my script is using the GT06 protocol rather than the Traccar REST API.
> 
> EDIT: See the following page:
> 
> https://www.traccar.org/devices/
is it possible to make simple python code to update traccar data with raspberry pi along with GPS module like NEO-6M ?

**Comment by lmandres** [comment]
> > > > @onlinegill , was the Pi Zero issue resolved by commenting out the section?
> > > > Yes and no.
> > > > Script runs now and I can see GPS information in terminal but it does not post on traccar server
> > > 
> > > 
> > > FYI : ESP32 client project is here and its working. https://github.com/onlinegill/ESP32-Traccar-GPS
> > 
> > 
> > So, looking at your code, my code might not be working because my script is using the GT06 protocol rather than the Traccar REST API.
> > EDIT: See the following page:
> > https://www.traccar.org/devices/
> > is it possible to make simple python code to update traccar data with raspberry pi along with GPS module like NEO-6M ?

Yes, it's possible.  However, I will not be able to get to it until after the holidays here in the US.  Let me see what I can do.
