### ISSUE TITLE
error GT06ScannerClient.py

### ISSUE THREAD

**Issue by mavmala** [lmandres/GT06ScannerClient#6]
Hello,

I am trying to make this work, I can start the python venv but if i run the runClient.py i get the following error:

 File "runClient.py", line 3, in <module>
    import GT06ScannerClient
  File "/home/ubilinux/GT06ScannerClient/GT06ScannerClient.py", line 9, in <module>
    import gt06Client
  File "/home/ubilinux/GT06ScannerClient/gt06Client.py", line 47
    logging.exception(f"Cannot connect to {self.serverAddress}:{self.serverPort}")

I edited the confix.xml to use my server and portnr, but I have no idea how to continue

any help?
TIA

**Comment by lmandres** [comment]
Hi @mavmala .  Does it work if you use the demo.traccar.org address that comes default in the config.xml file?

**Comment by mavmala** [comment]
Hi, thanks for answering!

No it gives errors as well.although different ones:

Hello from the pygame community. https://www.pygame.org/contribute.html
Namespace(config='config.xml', gps_baud=None, gps_port=None, id=None, magnification=None, maps_url=None, server_address=None, server_port=None, update_delay=None, zoom=None)
Traceback (most recent call last):
  File "runClient.py", line 78, in <module>
    mapsMagnificationIn=args.magnification
  File "/home/ubilinux/GT06ScannerClient/GT06ScannerClient.py", line 36, in __init__
    self.configReader = configReader.ConfigReader(configFile)
  File "/home/ubilinux/GT06ScannerClient/configReader.py", line 12, in __init__
    self.configXML = ElementTree.parse(fileName)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by mavmala** [comment]
This is the message I get:

XML Parsing Error: mismatched tag. Expected: </heading>.
Location: https://www.w3schools.com/xml/xml_validator.asp
Line Number 5, Column 20:
<heading>Reminder</pheading>
-------------------^

**Comment by lmandres** [comment]
Yeah.  If the XML is the same, that's the Hostname line.  You can try copy and pasting the demo tag to make sure that it's correct:

<Hostname>demo.traccar.org</Hostname>

You'll need to make sure the case on the tags is the same.

**Comment by mavmala** [comment]
copy & pasted it, still the same error:

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Namespace(config='config.xml', gps_baud=None, gps_port=None, id=None, magnification=None, maps_url=None, server_address=None, server_port=None, update_delay=None, zoom=None)
Traceback (most recent call last):
  File "runClient.py", line 78, in <module>
    mapsMagnificationIn=args.magnification
  File "/home/ubilinux/GT06ScannerClient/GT06ScannerClient.py", line 36, in __init__
    self.configReader = configReader.ConfigReader(configFile)
  File "/home/ubilinux/GT06ScannerClient/configReader.py", line 12, in __init__
    self.configXML = ElementTree.parse(fileName)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by mavmala** [comment]
downloaded the config.xml again, and now it gives another error

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Namespace(config='config.xml', gps_baud=None, gps_port=None, id=None, magnification=None, maps_url=None, server_address=None, server_port=None, update_delay=None, zoom=None)
ERROR:root:ScannerID is expected to be HEX value
Traceback (most recent call last):
  File "/home/ubilinux/GT06ScannerClient/configReader.py", line 25, in getScannerID
    bytes.fromhex(scannerID)
ValueError: non-hexadecimal number found in fromhex() arg at position 4

**Comment by lmandres** [comment]
In the XML file, check this line:

<ScannerIDNumber>0123456789012345</ScannerIDNumber>

There should only be numerical digits (0-9) or hex digits (a-f).  Other characters would make it fail.
